FROM --platform=linux/x86-64 public.ecr.aws/amazonlinux/amazonlinux:latest

# https://docs.aws.amazon.com/dms/latest/sbs/chap-mongodb2documentdb.02.html
    # https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-amazon/
COPY docker/setup_files/mongodb.repo /etc/yum.repos.d/mongodb-org-7.0.repo

RUN yum update -y
RUN yum install -y httpd
RUN yum install -y mongodb-org
RUN yum remove -y mongodb-mongosh
RUN yum install -y mongodb-mongosh-shared-openssl3
RUN yum install -y mongodb-org

# TODO: add script to setup db

# RUN systemctl enable mongod --now

RUN yum install -y python3

COPY ../src /app
COPY requirements.txt /app
# RUN pip3 install -r requirements.txt
WORKDIR /app

EXPOSE 27017

### docker-compose example ###
# https://github.com/compwright/amazonlinux-2023-systemd/tree/master
#  TODO: figure out how to manange file location discrepancies with docker-compose
RUN dnf install -y systemd kernel-libbpf
CMD ["/usr/sbin/init"]

### TESTING ###
# COPY docker/setup_files/start-systemd.sh /usr/sbin/start-systemd.sh
# CMD ["/usr/sbin/start-systemd.sh"]

# ENTRYPOINT [ "bash" ]