name: Pylint

on: [push]

jobs:
  build:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f bot/requirements.txt ]; then pip install -r bot/requirements.txt; fi

    - name: Analysing the code with pylint
      run: |
        pylint --fail-under 8 $(git ls-files '*.py')
